-- AlterTable
ALTER TABLE "Imprimante" ADD COLUMN "compteursInitiauxSaisis" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Imprimante" ADD COLUMN "dateCompteursInitiaux" DATE;
ALTER TABLE "Imprimante" ADD COLUMN "c112Init" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Imprimante" ADD COLUMN "c113Init" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Imprimante" ADD COLUMN "c122Init" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Imprimante" ADD COLUMN "c123Init" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Imprimante" ADD COLUMN "c501Init" INTEGER;
ALTER TABLE "Imprimante" ADD COLUMN "scanNoirInit" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Imprimante" ADD COLUMN "scanCouleurInit" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Imprimante" ADD COLUMN "envoiInit" INTEGER NOT NULL DEFAULT 0;
